sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
branches:
  only:
    - master # build master branch only
cache:
  directories:
    - node_modules
before_script:
  - git clone https://github.com/zongzi531/hexo-theme-Journal.git themes/journal
  - yarn install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
