sidebar_title: "Zong"
sidebar_subtitle: "人之所以能<br>，是相信能"

truncate_len: 60

rss: # atom.xml
archives: false

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: zongzi # [short_name] for disqus.com

# Declare license on posts
post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/
